version: '3'
services:
  postgresql:
    image: postgres:15
    container_name: jb-products-info_postgres
    ports:
      - "11050:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: jb-products-info
      POSTGRES_HOST_AUTH_METHOD: trust