server:
  jetty:
    threads:
      min: 20
      max: 20
  port: 12001
spring:
  datasource:
    hikari:
      idle-timeout: 10000
      connection-timeout: 1000
      maximum-pool-size: 5
      pool-name: ${spring.application.name}
    url: jdbc:postgresql://127.0.0.1:11050/${spring.application.name}
    username: postgres
    password: pwd
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
      ack-mode: manual_immediate
      concurrency: 2
    consumer:
      auto-offset-reset: earliest
      group-id: jb-products-info-worker
      properties:
        max:
          poll:
            interval:
              ms: 600000 # 10 minutes
            records: 1
        request:
          timeout:
            ms: 900000 # 15 minutes
    producer:
      client-id: jb-products-info
kafka:
  builds-to-process:
    concurrency: 1
    nack-sleep-time-seconds: 180